"""asdaa

Revision ID: d2f541d6d851
Revises: 7942b714d9d4
Create Date: 2024-03-18 21:51:07.830056

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2f541d6d851'
down_revision: Union[str, None] = '7942b714d9d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_event', sa.Column('details', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_event', 'details')
    # ### end Alembic commands ###
